server:
  port: 9000
  servlet:
    contextPath: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: @username@
    password: @password@
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
  application:
    name: visitor-service

queue:
  visitors: @queue@

path:
  api: /api/v1

cloud:
  aws:
    credentials:
      access-key: @accessKey@
      secret-key: @secretKey@
    region:
      static: us-east-1